- type: job
  id: AdministratorNCWL
  name: job-name-administrator
  description: job-description-administrator
  playTimeTracker: JobAdministratorNCWL
  weight: 60
  startingGear: AdministratorGear
  alwaysUseSpawner: true
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  requirements:
    - !type:WhitelistRequirement
  supervisors: job-supervisors-highcomm 
  canBeAntag: false
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - NCWLAdministrator
  - NCWLGeneral
  - NCWLArmory
  - NCWLCommand
  - NCWLJail
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: AdministratorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNCWLCommunications
    back: ClothingBackpackSatchelLeatherFilledNCWLAdministrator
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatNCWLBeretAdmiral
    id: AdministratorPDA
    ears: ClothingHeadsetNCWL
    belt: WeaponRevolverPythonAP
    pocket1: NCWLPassportAccepted
